ifndef MAKEFILE_CXX
define MAKEFILE_CXX
yes
endef

APP_ROOT := ..
CXXFILES += \
    cxx.cpp

INCPATH += \
    -I.

LD_FLAGS += \
    -lstdc++_nano

TARGET := cxx.mo

include $(APP_ROOT)/SDK/cplusplus/Makefile.local
include $(APP_ROOT)/SDK/Makefile.common

endif