ifndef MAKEFILE_NEWLIB_LOCAL
define MAKEFILE_NEWLIB_LOCAL
yes
endef

CFILES  +=  \
	../newlib/lib_reent.c \
	../newlib/lib_svcbase.c \
	../newlib/lib_syscalls.c \
	../newlib/lib_crt0.c

INCPATH += \
	-I../newlib/include
	
DEFINES += \
	-DRT_USING_NEWLIB

endif # MAKEFILE_NEWLIB_LOCAL