ifndef MAKEFILE_TFLITE
define MAKEFILE_TFLITE
yes
endef

include ./Makefile.local
include ../newlib/Makefile.local
include ../cplusplus/Makefile.local
include ../tflite-mcu/Makefile.local
include ../Makefile.common

endif